### PR TITLE
Add options

### PR DESCRIPTION
**Pull request by ackintosh**
With reference to [quipper/fluent-plugin-http_shadow](https://github.com/quipper/fluent-plugin-http_shadow), I added two options I want to use with original.

- rate_per_method_hash
  - https://github.com/quipper/fluent-plugin-http_shadow/pull/1/commits/dd3410dfcb5354b5766b7561dd144a265d3a2235
- support_methods
  - https://github.com/quipper/fluent-plugin-http_shadow/pull/2/commits/db85336abed7adaef998c40e3a831a43dbcf1118

### CODE REVIEW

**Comment by ackintosh** [comment]
@toyama0919 Please review 🙏 ✨

**Comment by toyama0919** [comment]
@ackintosh 
Sorry, late response!!
LGTM, thanks.

**Comment by ackintosh** [comment]
Thanks!

**Comment by toyama0919** [comment]
released.

[fluent\-plugin\-http\_shadow \| RubyGems\.org \| your community gem host](https://rubygems.org/gems/fluent-plugin-http_shadow)

**Pull request merged**
